### ISSUE TITLE
¿Cómo puedo ver el consumo de este mes?

### ISSUE THREAD

**Issue by adocampo** [duhow/hass-aigues-barcelona#14]
Hola!

Acabo de dar con este addon, he entrado sin problemas como se indica en el thread correspondiente y he añadido una tarjeta para ver mi consumo. En la tarjeta sale lo que es el consumo total del contador (porque como aparece una coma, entiendo que es el separador americano de los millares).
![image](https://github.com/duhow/hass-aigues-barcelona/assets/2266612/03a8db53-3bcd-4c03-8901-e7ecdb274325)
![image](https://github.com/duhow/hass-aigues-barcelona/assets/2266612/e08b2ac6-a380-477b-a433-985ca2ab18d5)

Me pregunto si podemos ver el consumo que llevamos de mes, en lugar del total del contador.

Muchas gracias por responder y por desarrollar este addon!

**Comment by duhow** [comment]
Hola!

El addon sólo almacena el último dato disponible en Home Assistant, y la idea es que usando los `records` de Home Assistant se pueda visualizar esto mismo.
Por otro lado todavía queda pendiente realizar la integración con el sistema de Energía y cargar datos historicos anteriores para poder visualizarlos.
De momento se puede agregar la entidad para guardar las diferencias entre lecturas.

Las medidas de consumo que devuelve la API son en m3 (1m3 = 1000 l).

**Comment by adocampo** [comment]
> la idea es que usando los `records` de Home Assistant se pueda visualizar esto mismo
No sé cómo llevar a cabo eso...

**Comment by duhow** [comment]
Los `records` es el histórico de datos almacenados en Home Assistant, tienes que configurarlo acorde a lo que necesites.

**Comment by adocampo** [comment]
el histórico sí que sé verlo, pero me refería a algún método para que hiciera los cálculos y que me mostrara la diferencia entre el total del mes anterior y la última medida, así sabría mi consumo en curso.
