### ISSUE TITLE
[Feature request] Acceso a los datos horarios proporcionados por la telelectura

### ISSUE THREAD

**Issue by cdeharo** [duhow/hass-aigues-barcelona#15]
En algunos municipios ya se ha desplegado el [contador con telelectura](https://www.aiguesdebarcelona.cat/es/web/guest/tu-servicio-de-agua/mi-factura-consumo/telelectura) que permite obtener el consumo realizado por hora. 

Sería muy interesante disponer de esta información también en Home Assistant.

Gracias

**Comment by duhow** [comment]
Hacer un backfilling de datos históricos en Energía (consumo de agua). Si, está en el roadmap pendiente.

**Comment by duhow** [comment]
![image](https://github.com/duhow/hass-aigues-barcelona/assets/1145001/c099ce11-7d6b-4d39-8377-67fd519dba10)

**Comment by diamant-x** [comment]
Wow! Pero no lo cierres con el pantallazo y nos dejes con la miel en los labios crack! jaja
¿Cómo funciona?
¿Hasta cuanto tiempo atrás hace 'back injection'?
¿Cual es la granularidad (en la foto se ven cuadres a nivel dia, pero son la suma de los cuadres a nivel horario)?
¿Tenemos que hacer algo a nivel de usuario para que funcione?
¿Hay alguna limitación conocida?

Muchas gracias!

**Comment by duhow** [comment]
- De momento es sólo desde 1 semana atrás, miraré de que en "nuevas instalaciones" intente recuperar más información.
- La información que se agrega es "por horas" en un día, Home Assistant ya hace la magia de mostrar la información por semana (y espero por mes también).
- Con agregar el sensor / contador en Energía, se debería mostrar la información.

Es bastante posible que haya fallos conforme tengamos más datos históricos, si es así por favor abrid una nueva issue.
