### ISSUE TITLE
Corrección de medidas totales del dia en el panel de Energia (nuevo tras back-injection horario)

### ISSUE THREAD

**Issue by diamant-x** [duhow/hass-aigues-barcelona#18]
Hola,

He probado la nueva versión https://github.com/duhow/hass-aigues-barcelona/issues/15 y tiene pinta de funcionar perfectamente. A excepción de una cosa.
Veo que en los dias del pasado donde ya actualicé el sensor y se apuntó en una hora todo el consumo acumulado desde el ultimo refresco, ahora en la hora siguiente se le resta todo ese agua. Por lo que la suma total del dia es correcta, pero hace imposible apreciar los cambios horarios al ser diminutos en comparación.

- La herramienta lo borrará a partir de ahora, en lugar de escribir un valor negativo para compensar?

si decido hacer el esfuerzo de manualmente editar el registro, 

- Qué entidad o estadistica debo editar?
He mirado y solo veo la entidad del contador de agua, que siempre me muestra el total.

![image](https://github.com/duhow/hass-aigues-barcelona/assets/7346338/7466d50c-9adc-4139-81ff-023481b85d0e)

**Comment by duhow** [comment]
El problema es debido a la forma en la que Home Assistant guarda las `statistics`, es con el `state` (valor total) y el `sum` (incremento acumulado).

Supongamos que partes de lectura de consumo 300 m3, gastas 0.1 en una hora, y la siguiente hora no gastas (0.0) .
El problema es que el último valor de `sum` es 0.0, en vez de 0.1 + 0.0 , con lo que se representa de forma negativa.

**Comment by diamant-x** [comment]
Quieres decir que no se puede arreglar?

No se si lo estoy entendiendo. Lo que ese comportamiento solo ocurre en la hora inmediatamente posterior a la que antiguamente registró el delta del contador. En días donde no actualice los datos, salen bien representados en cada hora.

**Comment by duhow** [comment]
Se puede arreglar.

**Comment by Davegee77** [comment]
Hola,
Me pasa igual, como se arregla?

**Comment by miguelfrancisco85** [comment]
hola, me gustaria saber como puedo ayudar para arreglar el problema de los valores negativos
