### ISSUE TITLE
.

### ISSUE THREAD

**Issue by BKF73** [duhow/hass-aigues-barcelona#33]
Hola,
He probado master y copiando el token de las cookies y me funciona correctamente.
Igual estaría bien explicarle a la gente el paso a paso, por si se pierden un poco:

1. Cambiar version a master
2. Reiniciar
3. Añadir dispositivo
4. Abrir en otro navegador la web de aigües de barcelona y hacer login
5. Como sacar el token en chrome: click derecho inspeccionar sobre la web de aigües de barcelona
6. Ir a la pestaña de application
7. Ir a cookies en el lado izquierdo y buscar ofexTokenJwt
8. Copiar el valor de la cookie a la pantalla de Token de HA

Un saludo

_Originally posted by @PutoPunko in https://github.com/duhow/hass-aigues-barcelona/issues/5#issuecomment-1455715609_

**Comment by BKF73** [comment]
Hola, soy novato en este del Home Assistant , me podeis decir como hacer el primer punto , el "cambio a version master" ??

**Comment by duhow** [comment]
Eso es de hace 1 año y no es necesario.
