### ISSUE TITLE
El valor del sensor siempre es -1

### ISSUE THREAD

**Issue by oalbaf** [duhow/hass-aigues-barcelona#4]
Hola!

Ayer instalé la integración y ha aceptado mis credenciales para AGBAR sin problemas, presentándome el número de contrato correcto. Pero el valor del sensor es constantemente -1, y en el LOG tengo el siguiente mensaje. 

`2023-01-21 09:41:06.412 ERROR (MainThread) [custom_components.aigues_barcelona.sensor] No consumptions available`

Mi contador tiene telelectura y puedo ver el consumo por horas en la web de Aigües de Barcelona. El valor de consumo en estos momentos es 0m3, pero que el sensor marque -1 y el LOG me hacen pensar que quizás no me está funcionado la integración.

¿Estoy siendo impaciente y debo esperar a que se actualice el sensor o realmente hay un problema para que la integración pueda acceder a mi consumo?

Muchas gracias y ánimo con la integración. Si puedo colaborar, aunque sea como beta tester, estaré encantado.

Saludos,

**Comment by oalbaf** [comment]
Paciencia. Ese ha sido el problema!. Ahora miraré si puedo en HA adaptar el valor para poder usarlo en el panel de energia

**Comment by duhow** [comment]
Debería estar resuelto en 2c9ca701db13f4a35cb4f21e3102cf8aa63c90f4 .
